version: '3.5'

services:
  mail-redis:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          memory: 52M

volumes:
  mail-redis-vol:
    name: mail-redis-vol
