version: '3.5'

services:
  mail-mailserver:
    image: hardware/mailserver:${IMAGE_TAG:-latest}
    hostname: ${HOST_NAME}
    networks:
      - mail-net
      - traefik-net
    volumes:
      - mail-mailserver-vol:/var/mail
    environment:
      - DOMAIN
      - REDIS_HOST
      - DBHOST
      - DBPASS
      - RSPAMD_PASSWORD
      - ADD_DOMAINS

networks:
  mail-net:
    external: true
  traefik-net:
    external: true
