version: '3.5'

services:
  mailserver:
    image: hardware/mailserver:${IMAGE_TAG:-latest}
    domainname: redmic.es # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: mail
    networks:
      - mail-net
    volumes:
      - mailserver-vol:/var/mail
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - DBPASS # MariaDB database password (required)
      - RSPAMD_PASSWORD # Rspamd WebUI password (required)
    # - ADD_DOMAINS=aa.tld, www.bb.tld... # Add additional domains separated by commas (needed for dkim keys etc.)
    # - ENABLE_POP3=true # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true # Enable fetchmail forwarding
    # - DISABLE_CLAMAV=true # Disable virus scanning
    # - DISABLE_SIGNING=true # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true # Disable greylisting policy
    # - DISABLE_RATELIMITING=true # Disable ratelimiting policy
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #

networks:
  mail-net:
    external: true
