version: '3.5'

services:
  mail-mailserver:
    ports:
      - target: 25
        published: 25
        mode: host
      - target: 143
        published: 143
        mode: host
      - target: 587
        published: 587
        mode: host
      - target: 993
        published: 993
        mode: host
      - target: 4190
        published: 4190
        mode: host
      - target: ${RSPAMD_PORT}
        published: ${RSPAMD_PORT}
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${RSPAMD_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: Host:spam.${PUBLIC_HOSTNAME}
        traefik.backend: mailserver
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          memory: 820M

volumes:
  mail-mailserver-vol:
    name: mail-mailserver-vol
