version: '3.5'

services:
  prometheus:
    container_name: prometheus
    restart: on-failure:3
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}

volumes:
  prometheus-vol:
    name: prometheus-vol
