version: '3.5'

services:
  traefik:
    image: traefik:${IMAGE_TAG:-latest}
    command:
      - "--api"
      - "--docker"
      - "--docker.domain=traefik"
      - "--docker.watch"
    networks:
      - redmic-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  redmic-net:
    external: true
