version: '3.5'

services:
  traefik:
    command:
      - "--logLevel=ERROR"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS:/ssl/certFile.cert,/ssl/keyFile.key"
      - "--defaultentrypoints=http,https"
      - "--docker.swarmmode"
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-net
    secrets:
      - source: certFile-secret
        target: /ssl/certFile.cert
      - source: keyFile-secret
        target: /ssl/keyFile.key
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "8080"
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic: ${UI_AUTH}
        traefik.frontend.rule: Host:traefik.${PUBLIC_HOSTNAME}
        traefik.backend: traefik
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  traefik-net:
    external: true

secrets:
  certFile-secret:
    file: ./certFile.cert
  keyFile-secret:
    file: ./keyFile.key
