version: '3.5'

services:
  traefik:
    image: traefik:${IMAGE_TAG:-latest}
    command:
      - "--api"
      - "--forwardingtimeouts.dialtimeout=15s"
      - "--forwardingtimeouts.responseheadertimeout=15s"
      - "--respondingtimeouts.idletimeout=30s"
      - "--respondingtimeouts.readtimeout=1m"
      - "--respondingtimeouts.writetimeout=1m"
      - "--docker"
      - "--docker.domain=traefik"
      - "--docker.watch"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.entrypoint=traefik"  
    networks:
      - redmic-net
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  redmic-net:
    external: true
  traefik-net:
    external: true
