version: '3.5'

services:
  traefik:
    command:
      - "--logLevel=INFO"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--docker.swarmmode"
      - "--acme"
      - "--acme.onhostrule"
      - "--acme.email=info@redmic.es"
      - "--acme.storage=acme.json"
      - "--acme.entrypoint=https"
      - "--acme.httpchallenge.entrypoint=http"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "8080"
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic: ${UI_AUTH}
        traefik.frontend.rule: Host:traefik.${PUBLIC_HOSTNAME}
        traefik.backend: traefik
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '2'
          memory: 128M
        reservations:
          memory: 103M
