version: '3.5'

services:
  grafana:
    image: grafana/grafana:${IMAGE_TAG:-latest}
    networks:
      - redmic-net
    volumes:
      - grafana-vol:/var/lib/grafana

networks:
  redmic-net:
    external: true
