version: '3.5'

services:
  pgadmin:
    ports:
      - target: ${PGADMIN_PORT}
        published: ${PGADMIN_PORT}
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${PGADMIN_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: Host:pgadmin.${PUBLIC_HOSTNAME}
        traefik.backend: pgadmin
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          memory: 103M

volumes:
  pgadmin-vol:
    name: pgadmin-vol
