version: '3.5'

services:
  mail-mariadb:
    image: mariadb:${IMAGE_TAG:-latest}
    networks:
      - mail-net
    volumes:
      - mail-mariadb-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

networks:
  mail-net:
    external: true
