version: '3.5'

services:
  mail-mariadb:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          memory: 103M

volumes:
  mail-mariadb-vol:
    name: mail-mariadb-vol
