version: '3.5'

services:
  mail-postfixadmin:
    image: hardware/postfixadmin:${IMAGE_TAG:-latest}
    domainname: ${DOMAIN_NAME}
    hostname: mail-postfixadmin
    networks:
      - mail-net
    environment:
      - DBHOST
      - DBPASS
      - SMTPHOST

networks:
  mail-net:
    external: true
