version: '3.5'

services:
  mail-postfixadmin:
    image: hardware/postfixadmin:${IMAGE_TAG:-latest}
    domainname: redmic.net
    hostname: mail
    networks:
      - mail-net
    environment:
      - DBHOST=mail-mariadb
      - DBPASS

networks:
  mail-net:
    external: true
