version: '3.5'

services:
  mail-postfixadmin:
    ports:
      - "${POSTFIXADMIN_PORT}:8888"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "8888"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: Host:postfixadmin.${PUBLIC_HOSTNAME}
        traefik.backend: postfixadmin
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          memory: 52M
