concurrent = 2
check_interval = 10

[[runners]]
  name = "REDMIC GitLabCI Runner"
  url = "https://git.redmic.net"
  token = "${RUNNER_TOKEN}"
  executor = "docker"
  output_limit = 4096

  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = true
    disable_cache = true
    shm_size = 1000000000
    memory = "4g"
    memory_swap = "6g"
    memory_reservation = "1g"
    cpuset_cpus = "1,2"

  [runners.cache]
    Type = "s3"
    ServerAddress = "minio.redmic.net"
    AccessKey = "${MINIO_ACCESS_KEY}"
    SecretKey = "${MINIO_SECRET_KEY}"
    BucketName = "cache"
    Insecure = false
    Shared = true
