version: '3.5'

services:
  gitlab-runner-local:
    image: gitlab/gitlab-runner:${IMAGE_TAG:-latest}
    entrypoint: /bin/sh
    command: >
      -c "
        gitlab-runner register ;
        gitlab-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner"
    environment:
      - CONFIG_FILE
      - CI_SERVER_URL
      - REGISTRATION_TOKEN
      - REGISTER_NON_INTERACTIVE
      - REGISTER_LOCKED
      - REGISTER_RUN_UNTAGGED
      - RUNNER_NAME
      - RUNNER_TAG_LIST
      - RUNNER_REQUEST_CONCURRENCY
      - RUNNER_OUTPUT_LIMIT
      - RUNNER_EXECUTOR
      - DOCKER_IMAGE
      - DOCKER_TLS_VERIFY
      - DOCKER_PRIVILEGED
      - DOCKER_DISABLE_CACHE
      - DOCKER_SHM_SIZE
      - DOCKER_MEMORY
      - DOCKER_MEMORY_RESERVATION
      - DOCKER_CPUS
      - CACHE_TYPE
      - CACHE_SHARED
      - CACHE_S3_SERVER_ADDRESS
      - CACHE_S3_ACCESS_KEY
      - CACHE_S3_SECRET_KEY
      - CACHE_S3_BUCKET_NAME
      - CACHE_S3_INSECURE
    networks:
      - gitlab-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - etc-vol:/etc/gitlab-runner
      - home-vol:/home/gitlab-runner
    configs:
      - source: config-toml
        target: ${CONFIG_FILE}
        uid: '100'
        gid: '0'
        mode: 0660

networks:
  gitlab-net:
    external: true

configs:
  config-toml:
    file: ./config-local/config.toml
