version: '3.5'

services:
  gitlab-runner-local:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 1m
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          memory: 410M

volumes:
  etc-vol:
    name: gitlab-runner-local-etc-vol

  home-vol:
    name: gitlab-runner-local-home-vol
