version: '3.5'

services:
  gitlab-runner-remote:
    image: gitlab/gitlab-runner:${IMAGE_TAG:-latest}
    entrypoint: /bin/sh
    command: >
      -c "
        gitlab-runner register ;
        gitlab-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner"
    environment:
      - CONFIG_FILE
      - CI_SERVER_URL
      - REGISTRATION_TOKEN
      - REGISTER_NON_INTERACTIVE
      - REGISTER_LOCKED
      - REGISTER_RUN_UNTAGGED
      - RUNNER_NAME
      - RUNNER_TAG_LIST
      - RUNNER_LIMIT
      - RUNNER_REQUEST_CONCURRENCY
      - RUNNER_OUTPUT_LIMIT
      - RUNNER_EXECUTOR
      - CACHE_TYPE
      - CACHE_SHARED
      - CACHE_S3_SERVER_ADDRESS
      - CACHE_S3_ACCESS_KEY
      - CACHE_S3_SECRET_KEY
      - CACHE_S3_BUCKET_NAME
      - DOCKER_IMAGE=${RUNNER_DOCKER_IMAGE}
      - DOCKER_TLS_VERIFY=${RUNNER_DOCKER_TLS_VERIFY}
      - DOCKER_PRIVILEGED=${RUNNER_DOCKER_PRIVILEGED}
      - DOCKER_DISABLE_CACHE=${RUNNER_DOCKER_DISABLE_CACHE}
      - DOCKER_SHM_SIZE=${RUNNER_DOCKER_SHM_SIZE}
      - DOCKER_MEMORY=${RUNNER_DOCKER_MEMORY}
      - DOCKER_MEMORY_RESERVATION=${RUNNER_DOCKER_MEMORY_RESERVATION}
      - DOCKER_CPUS=${RUNNER_DOCKER_CPUS}
    networks:
      - gitlab-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - etc-vol:/etc/gitlab-runner
      - home-vol:/home/gitlab-runner

networks:
  gitlab-net:
    external: true
