version: '3.5'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:${IMAGE_TAG:-latest}
    command: |
      run \
        --user=gitlab-runner \
        --working-directory=/home/gitlab-runner
      register
    networks:
      - gitlab-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
    environment:
      - REGISTER_NON_INTERACTIVE=true
      - CI_SERVER_URL=${GITLAB_URL}
      - CI_SERVER_TOKEN=${GITLAB_TOKEN}
      - RUNNER_NAME
      - RUNNER_OUTPUT_LIMIT
      - RUNNER_EXECUTOR
      - DOCKER_IMAGE
      - DOCKER_TLS_VERIFY
      - DOCKER_PRIVILEGED
      - DOCKER_DISABLE_CACHE
      - DOCKER_SHM_SIZE
      - DOCKER_MEMORY
      - DOCKER_MEMORY_SWAP
      - DOCKER_MEMORY_RESERVATION
      - DOCKER_CPUSET_CPUS
      - CACHE_TYPE
      - CACHE_SHARED
      - S3_SERVER_ADDRESS=${MINIO_URL}
      - S3_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - S3_SECRET_KEY=${MINIO_SECRET_KEY}
      - S3_BUCKET_NAME
      - S3_CACHE_INSECURE

networks:
  gitlab-net:
    external: true
