version: '3.5'

services:
  gitlab-runner-remote:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          memory: 103M

volumes:
  etc-vol:
    name: gitlab-runner-remote-etc-vol

  home-vol:
    name: gitlab-runner-remote-home-vol
