version: '3.5'

services:
  gitlab-runner-remote:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 1m
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 820M
