version: '3.5'

services:
  portainer:
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  portainer-vol:
    name: ${PORTAINER_VOL_NAME:-portainer-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared
      perfmode: maxio
