version: '3.5'

services:
  gitlab-ce:
    ports:
      - target: 22
        published: ${GITLAB_SSH_PORT}
        mode: host
    secrets:
      - source: authorized_keys_proxy
        target: /gitlab-data/ssh/authorized_keys

volumes:
  config-vol:
    name: ${CONFIG_VOL_NAME:-gitlab-ce-config-vol}

  log-vol:
    name: ${LOG_VOL_NAME:-gitlab-ce-log-vol}

  data-vol:
    name: ${DATA_VOL_NAME:-gitlab-ce-data-vol}

secrets:
  authorized_keys_proxy:
    name: ${AUTHORIZED_KEYS_PROXY_NAME:-gitlab-authorized-keys-proxy}
    file: ./authorized_keys_proxy
