version: '3.5'

services:
  minio:
    image: minio/minio:${IMAGE_TAG:-latest}
    command: server /export
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    networks:
      - traefik-net
    volumes:
      - export-vol:/export
      - data-vol:/data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.rule: Host:minio.${PUBLIC_HOSTNAME}
        traefik.backend: minio
        traefik.port: '9000'
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 410M

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
