version: '3.5'

services:
  mail-rainloop:
    container_name: mail-rainloop
    restart: on-failure:3
    ports:
      - ${RAINLOOP_PORT}:8888

volumes:
  mail-rainloop-vol:
    name: mail-rainloop-vol
