version: '3.5'

services:
  mail-rainloop:
    image: hardware/rainloop:${IMAGE_TAG:-latest}
    networks:
      - mail-net
    volumes:
      - mail-rainloop-vol:/rainloop/data

networks:
  mail-net:
    external: true
