version: '3.5'

services:
  mail-rainloop:
    ports:
      - "${RAINLOOP_PORT}:8888"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "8888"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: Host:webmail.${PUBLIC_HOSTNAME}
        traefik.backend: rainloop
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          memory: 103M

volumes:
  mail-rainloop-vol:
    name: mail-rainloop-vol
